name: Karabiner-MultitouchExtension

targets:
  Karabiner-MultitouchExtension:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-MultitouchExtension
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/vendor/include
      HEADER_SEARCH_PATHS:
        - ../../lib/libkrbn/include
      OTHER_LDFLAGS:
        - -L../../lib/libkrbn/build/Release
        - -lkrbn
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      SWIFT_OBJC_BRIDGING_HEADER: src/Bridging-Header.h
    type: application
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
      - path: ../share/swift
        compilerFlags:
          - -Wall
          - -Werror
      - path: ../../../vendor/vendor/src/pqrs/osx/process_info
      - path: Resources
        excludes:
          - .gitignore
          - '*.plist.in'
    dependencies:
      - sdk: libc++.tbd
      - framework: /System/Library/PrivateFrameworks/MultitouchSupport.framework
