name: Karabiner-Elements CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: brew install
        run: brew install xcodegen
      - name: package
        run: make package
      - name: appendix
        run: ruby scripts/reduce-logs.rb 'make -C appendix'
      - name: tests
        run: ruby scripts/reduce-logs.rb 'make -C tests'
